version: '3'

networks:
  webnet:
    driver: ${NETWORKS_DRIVER}

volumes:
  redis:
    driver: ${VOLUMES_DRIVER}

services:
### PHP-FPM ###
  php-fpm:
    build:
      context: ./php-fpm
      args:
        - CHANGE_SOURCE=${CHANGE_SOURCE}
        - PHP_VERSION=${PHP_VERSION}
        - TZ=${TIMEZONE}
        - INSTALL_ADDITIONAL_LOCALES=${PHP_FPM_INSTALL_ADDITIONAL_LOCALES}
        - ADDITIONAL_LOCALES=${PHP_FPM_ADDITIONAL_LOCALES}
        - LOCALE=${PHP_FPM_DEFAULT_LOCALE}
        - PUID=${PHP_FPM_PUID}
        - PGID=${PHP_FPM_PGID}
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ./php-fpm/config/php/${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ${DOCUMENT_ROOT}:/var/www/html:cached
    # ports:
      # - "${PHP_FPM_PORT}:9000"
    restart: 'always'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 512M
    networks:
      - webnet

### NGINX ###
  nginx:
    build:
      context: ./nginx
      args:
        - CHANGE_SOURCE=${CHANGE_SOURCE}
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        # - PHP_UPSTREAM_PORT=${PHP_FPM_PORT}
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html:cached
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    restart: 'always'
    networks:
      - webnet

### Redis ###
  redis:
    build: ./redis
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ./redis/data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    # ports:
      # - "${REDIS_PORT}:6379"
    restart: 'always'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 512M
    networks:
      - webnet

### Workspace ###
  workspace:
    #image: laradock/workspace:latest-${PHP_VERSION}
    build:
       context: ./workspace
       args:
         - CHANGE_SOURCE=${CHANGE_SOURCE}
         - PHP_VERSION=${PHP_VERSION}
         - INSTALL_NODE=${WORKSPACE_INSTALL_NODE}
         - NODE_VERSION=${WORKSPACE_NODE_VERSION}
         - INSTALL_NPM_GULP=${WORKSPACE_INSTALL_NPM_GULP}
         - INSTALL_NPM_BOWER=${WORKSPACE_INSTALL_NPM_BOWER}
         - INSTALL_NPM_VUE_CLI=${WORKSPACE_INSTALL_NPM_VUE_CLI}
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html:cached
    restart: 'always'
    networks:
      - webnet

### Horizon ###
  horizon:
    build:
      context: ./horizon
      args:
        - PHP_VERSION=${PHP_VERSION}
        - CHANGE_SOURCE=${CHANGE_SOURCE}
        - PUID=${HORIZON_PUID}
        - PGID=${HORIZON_PGID}
    environment:
      - TZ=${TIMEZONE}
    restart: 'always'
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html:cached
      - ${HORIZON_LOG_DIR}:/var/log/horizon
      - ./horizon/supervisord.d:/etc/supervisord.d
    networks:
      - webnet

### Worker ###
  worker:
    build:
      context: ./worker
      args:
        - PHP_VERSION=${PHP_VERSION}
        - CHANGE_SOURCE=${CHANGE_SOURCE}
        - PUID=${HORIZON_PUID}
        - PGID=${HORIZON_PGID}
    environment:
      - TZ=${TIMEZONE}
    restart: 'always'
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html:cached
      - ${WORKER_LOG_DIR}:/var/log/worker
      - ./worker/supervisord.d:/etc/supervisord.d
    networks:
      - webnet